config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :api do
    namespace :v1 do
      post "users/sign_in", to: "sessions#create"
      delete "users/sign_out", to: "sessions#destroy"
      post "users/sign_up", to: "registrations#create"
      resources :notes, only: [ :index, :show ]
    end
  end
   
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "notes#index"
  resources :notes, only: [ :index, :create, :edit, :new, :update, :destroy, :show ] do
    post :remove_add_form, on: :collection
    post :remove_content, on: :collection
    # collection do
    #   post :remove_add_form
    #   post :remove_content
    # end
  end
  resources :friendships, only: [ :index, :create, :update, :destroy ] do
    member do
      post :send_friend_request
      post :accept
      post :reject
      delete :remove_friend
    end

    collection do
      get :pending_requests
    end
  end
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  access     :string           default("public")
#
class Note < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  has_many_attached :note_images
  validate :validate_note_images
  validates :access, inclusion: { in: %w[public friend onlyme] }
  after_create_commit -> { broadcast_prepend_to "notes", partial: "shared/note", locals: { note: self }, target: "notes_list" }
  after_update_commit -> { broadcast_update_to "notes", partial: "shared/note", locals: { note: self  } }
  after_destroy_commit -> { broadcast_remove_to "notes" }

  def self.search_by_title(query)
    query = Array(query).first.to_s.downcase
    joins(:user)
      .where("LOWER(notes.title) LIKE :query OR LOWER(notes.content) LIKE :query OR LOWER(users.username) LIKE :query", query: "%#{query}%")
  end


  private
  def validate_note_images
    return unless note_images.attached?
    note_images.each do |image|
      unless image.content_type.in?(%w[image/jpg image/png image/jpeg])
        errors.add(:image, " must be a PNG,JPG, or JPEG file")
      end

      if image.byte_size > 5.megabytes
        errors.add(:image, "is too large (must be less then 5 MB)")
      end
    end
  end
end

app/controllers/api/v1/notes_controller.rb
class Api::V1::NotesController < Api::V1::ApplicationController
  before_action :authenticate_user!

  def index
    render json: Note.all, each_serializer: NoteSerializer, status: :ok
  end

  def show
    begin
      @note= Note.find(params[:id])
      render json: @note, status: :ok
    rescue ActiveRecord::RecordNotFound
      render json: { error: "Record not found" }, status: :not_found
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [ :edit, :show, :update, :destroy ]
  before_action :authenticate_user!
  def index
    if params[:search].present?
      @notes=Note.search_by_title(params[:search])
      flash[:notice]=""
      unless @notes.any?
        @notes= Note.all.order(created_at: :desc)
        flash[:notice] = "No notes found for \"#{params[:search]}\". Showing all notes."

      end
    else
      @notes = Note.all.order(created_at: :desc)
    end
    #  @pagy, @notes =pagy(@notes)
    # @notes= @notes.sample(@notes.length)
  end

  def new
    @note = Note.new
  end
  def create
    @note= Note.new(note_params)
    if @note.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Note was added successfully."}
        format.turbo_stream 
      end
    else
      flash[:alert]="Failed to Add Note."
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    # @note=Note.find(params[:id])
  end
  def show
    # @note=Note.find(params[:id])
  end
  def update
    # @note=Note.find(params[:id])
    if @note.update(note_params)
      respond_to do |format|
        redirect_to root_path, notice: "Note was updated successfully."
        format.turbo_stream
      end
    else
      flash[:alert]="Failed to Update Note."
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    # @note=Note.find(params[:id])
    if @note.destroy
      flash[:notice]="Note was deleted successfully."
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream
      end
    else
      flash[:alert]="Failed to Delete Note."
      redirect_to root_path

    end
  end

  def remove_add_form
    respond_to do |format|
      format.turbo_stream
    end
  end

  def remove_content
    respond_to do |format|
      format.html { redirect_to root_path }
      format.turbo_stream
    end
  end

  private
  def note_params
    params.require(:note).permit(:title, :content, :access, note_images: []).merge(user_id: current_user.id)
  end

  def set_note
    begin
      @note=Note.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert]="Note not found!!!"
      redirect_to root_path
    end
  end
end

app/helpers/api/v1/notes_helper.rb
module Api::V1::NotesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def can_edit_note?(note)
    current_user&.id == note.user_id
  end
end

app/views/notes/create.turbo_stream.erb
<%#turbo_stream.prepend "notes_list" do%>
    <%#turbo_frame_tag "notes_#{@note.id}" do%>
        <%#render "shared/note", note:@note, current: true%>
    <%#end%>
    
<%#end%>

<%= turbo_stream.update "add_note","" %>
<%#turbo_stream.replace "flash", partial:"shared/flash"%>

app/views/notes/destroy.turbo_stream.erb
<%= turbo_stream.remove "note_#{@note.id}"%>

app/views/notes/edit.html.erb
<%# render "shared/addNotes", note: @note %>

<%=turbo_frame_tag "note_#{@note.id}" do%>
    <%= render "shared/addNotes", note: @note ,heading: "Edit Note"%>
<%end%>

app/views/notes/index.html.erb
<%=turbo_stream_from "notes" %>
<div class="md:flex overflow-x-hidden">
<%# <div class=" flex-none w-[80px] max-w-[300px] bg-gray-200 shadow-md py-4 px-2  "> %>
    <div class="md:w-1/6 flex flex-col py-2 px-3  gap-2">

        <%=form_with url:notes_path, method: :get do%>
            <div class="flex gap-2">
                <%=text_field_tag :search, params[:search] , placeholder:"Search notes...", class:"p-2 border rounded w-full border-blue-300 focus:border-blue-600 dark:text-black", required:true %>
                <%=submit_tag "Search",class:"p-2 bg-blue-500 text-white rounded cursor-pointer hover:bg-blue-600"%>
                
                

            </div>
        <%end%>
        <%=link_to new_note_path,class:"px-4 py-2 mt-4  border border-blue-500 rounded hover:bg-blue-500 hover:text-white ",data:{turbo_frame:"add_note"} do%>
            <i class="fa-solid fa-plus"></i> <span class="ml-2">Add Notes</span>
        <%end%>
        
        <%=link_to friendships_path,class:"px-4 py-2 mt-4  border border-blue-500 rounded hover:bg-blue-500 hover:text-white" do%>
            <i class="fa-solid fa-people-group"></i> <span class="ml-2">All People</span>
        <%end%>
        <%=link_to pending_requests_friendships_path(current_user.id),class:"px-4 py-2 mt-4  border border-blue-500 rounded hover:bg-blue-500 hover:text-white" do%>
            <i class="fa-solid fa-users-rays"></i> <span class="ml-2">Friend Requests</span>
        <%end%>
        
        
    </div>
    <div class="flex flex-col flex-grow md:w-3/6">
        <%#  %>
        <%#  %>
        
        <%= turbo_frame_tag "add_note"  %>
        <div id="notes_list" class=" w-full grid grid-cols-2 lg:grid-cols-3 ">
                
                <%@notes.each do |note|%>
                    <%if (current_user.friend?(note.user_id) || note.access == "public" || note.user_id == current_user.id) && note.access!="onlyme"%>
                        
                            <%#current_user.id == note.user_id ? current=true : current=false%>

                            <%=render "shared/note", note: note%>
                        
                    
                    <%elsif (note.access == "onlyme") && (note.user_id == current_user.id)%>
                          
                            <%=render "shared/note", note: note%>
                        
                    <%end%>
                <%end%>
            
        </div>
        <div class="flex justify-center mt-5">
             <style>
                .pagy.nav {
                    display: flex;
                    justify-content: center;
                    gap: 8px;
                    padding: 10px 0;
                    font-family: Arial, sans-serif;
                    font-size: 16px;
                }

                .pagy.nav a {
                    padding: 8px 12px;
                    background-color: #f0f0f0;
                    border: 1px solid #ddd;
                    border-radius: 4px;
                    color: #333;
                    text-decoration: none;
                }

                .pagy.nav a:hover {
                    background-color: #e0e0e0;
                }

                .pagy.nav a.current {
                    background-color: #007bff;
                    color: white;
                    border: 1px solid #007bff;
                    cursor: not-allowed;
                }
                </style>
            <%#pagy_nav(@pagy) if @pagy.pages > 1 %>
        </div>
    </div >
    <div class="w-full md:w-2/6 ">
        
       <%=turbo_frame_tag "content"%>

    </div>
</div>

app/views/notes/new.html.erb
<%=turbo_frame_tag "add_note" do%>
    <%=render "shared/addNotes", note:@note ,heading:"Add New Note"%>
<%end%>

app/views/notes/remove_add_form.tubo_stream.erb
<%=turbo_stream.remove "add_note"%>

app/views/notes/remove_content.turbo_stream.erb
<%=turbo_stream.remove "content"%>

app/views/notes/show.html.erb
<%=turbo_frame_tag "content" do%>
<div class="w-[90%] mx-auto px-4 py-2 border rounded border-blue-300 my-2 shadow-xl">
    <div class="flex justify-between gap-1 mb-2">
                <%if request.headers["Turbo-Frame"] || request.headers["Turbo-Visit"]%>
                <div class="flex ml-auto">
                    <%=link_to remove_content_notes_path do%>
                    <span class="text-red-300 hover:text-red-600"><i class="fa-solid fa-xmark"></i></span>
                    <%end%>
                </div>
            <%end%>     
    </div>
    <h2 class="text-center whitespace-pre-wrap break-words text-blue-400 text-2xl p-3 "> <%=@note.title.upcase%></h2>
    <pre class="p-3 min-h-[50vh] whitespace-pre-wrap break-words bg-gray-100 rounded border border-gray-300 overflow-x-auto dark:bg-gray-700 dark:text-white">
    <code class=""><%= @note.content %></code>
    </pre>
    <%# <div class="grid grid-cols-3 gap-4 mt-3"> %>
    <div class="flex flex-wrap gap-2 ">
        <%@note.note_images.each do |image|%>
            <%=image_tag url_for(image),alt:"note image",class:"h-48 object-cover rounded "%>
        <%end%>
    <div>
  
</div>

        
    </div>    
</div>
<%end%>

app/views/notes/update.turbo_stream.erb
<%=turbo_stream.update "note_#{@note.id}" do%>
    <%= render partial: "shared/note", locals: {note: @note , current: true}%>
<%end%>