config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :api do
    namespace :v1 do
      post "users/sign_in", to: "sessions#create"
      delete "users/sign_out", to: "sessions#destroy"
      post "users/sign_up", to: "registrations#create"
      resources :notes, only: [ :index, :show ]
    end
  end
   
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "notes#index"
  resources :notes, only: [ :index, :create, :edit, :new, :update, :destroy, :show ] do
    post :remove_add_form, on: :collection
    post :remove_content, on: :collection
    # collection do
    #   post :remove_add_form
    #   post :remove_content
    # end
  end
  resources :friendships, only: [ :index, :create, :update, :destroy ] do
    member do
      post :send_friend_request
      post :accept
      post :reject
      delete :remove_friend
    end

    collection do
      get :pending_requests
    end
  end
end

app/views/shared/_addNotes.html.erb
<div class="p-4 border rounded md:w-[90%] mx-auto mt-4 flex flex-col bg-gray-200 dark:bg-gray-900 dark:text-white">
  

      <%=link_to remove_add_form_notes_path ,class:"ml-auto" do%>
    <span class=" hover:text-red-600 text-red-300 p-2 rounded-full">
        <i class="fa-solid fa-xmark"></i>
    </span>
      <%end%>
    <h2 class="text-center text-blue-400 text-2xl "><%=heading%> </h2>

  <%= simple_form_for note do |f| %>
    <%= f.input :title, 
        autofocus: true,
        label_html: { class: "block text-gray-700 font-medium mb-1 dark:text-white" },
        input_html: { class: "block w-full border rounded mb-4 p-2 dark:text-black" } %>
    <%= f.input :note_images,label:"Note Images",
        as: :file,
        label_html: { class: "block text-gray-700 font-medium mb-1 dark:text-white" },
        input_html: { class: "block w-full border rounded mb-4 p-2 ",multiple:true,accept:"image/*" } %>
        
    <%= f.input :content, 
        as: :text, 
        wrapper_html: { class: "mb-4" }, 
        input_html: { class: "block w-full border rounded p-2 dark:text-black" },
        label_html: { class: "block text-gray-700 font-medium mb-1 dark:text-white" } %>
    <%= f.input :access,as: :select, collection:(%w[public friend onlyme]),include_blank: false,
    wrapper_html: { class: "mb-4" }, 
        input_html: { class: "block w-full border rounded p-2 dark:text-black" },
        label_html: { class: "block text-gray-700 font-medium mb-1 dark:text-white" }
    %>
    <%= f.submit "Save", 
        class: "w-full border border-blue-600 p-2 rounded hover:bg-blue-500 hover:text-white" %>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<p class="notice text-center text-red-500 border border-green-400"><%= notice %></p>
<p class="alert text-center text-xl border border-red-500 text-red-500"><%= alert %></p>

app/views/shared/_footer.html.erb
<!-- This is an example component -->
<div class=" bg-gray-700 mt-4">
    <div class="max-w-2xl mx-auto text-white py-5 pt-8">
        <div class="text-center">
            <h3 class="text-3xl mb-3"> Download our ColabNotes app </h3>
            <p> Note. Collaborate. Anytime, anywhere. </p>
            <div class="flex justify-center my-10">
                <div class="flex items-center border w-auto rounded-lg px-4 py-2 w-52 mx-2">
                    <img src="https://cdn-icons-png.flaticon.com/512/888/888857.png" class="w-7 md:w-8">
                    <div class="text-left ml-3">
                        <p class='text-xs text-gray-200'>Download on </p>
                        <p class="text-sm md:text-base"> Google Play Store </p>
                    </div>
                </div>
                <div class="flex items-center border w-auto rounded-lg px-4 py-2 w-44 mx-2">
                    <img src="https://cdn-icons-png.flaticon.com/512/888/888841.png" class="w-7 md:w-8 ">
                    <div class="text-left ml-3">
                        <p class='text-xs text-gray-200'>Download on </p>
                        <p class="text-sm md:text-base"> Apple Store </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-26 flex flex-col md:flex-row md:justify-between items-center text-sm text-gray-400">
            <p class="order-2 md:order-1 mt-8 md:mt-0"> &copy; Habi Pyatha, 2024. </p>
            <div class="order-1 md:order-2">
                <span class="px-2">About us</span>
                <span class="px-2 border-l">Contact us</span>
                <span class="px-2 border-l">Privacy Policy</span>
            </div>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="relative select-none bg-grey lg:flex lg:items-center w-full bg-gray-700">
  <div class="flex flex-no-shrink items-stretch h-12">
    <%= link_to "ColabNotes",root_path,class:"flex-no-grow flex-no-shrink relative ml-3 py-2 px-4 leading-normal text-xl text-white no-underline flex items-center hover:text-green-600"%>
    
  </div>
  <div class="lg:flex lg:items-stretch lg:flex-no-shrink lg:flex-grow">
    <%#  %>
  <div class=" ml-auto justify-center flex flex-row items-center transition-all ease-in-out">
    <div class="flex flex-row justify-between toggle">
        <label for="dark-toggle" class="flex items-center cursor-pointer">
            <div class="relative">
            <input type="checkbox" name="dark-mode" id="dark-toggle" class="checkbox hidden">
            <div class="block border-[1px] dark:border-white border-white w-14 h-8 rounded-full"></div>
            <div class="dot absolute left-1 top-1 dark:bg-white bg-white w-6 h-6 rounded-full transition"></div>
            </div>
            <div class="ml-3 dark:text-white text-white font-medium">
            Dark Mode
            </div>
        </label>
        </div>
    </div>
    <%#  %>
    <div class="lg:flex lg:items-stretch lg:justify-end ml-auto">
    <%unless user_signed_in?%>
        <%= link_to "Sign In", new_user_session_path, class: "flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-white no-underline flex items-center hover:bg-green-500" %>
        <%= link_to "Sign Up", new_user_registration_path	, class: "flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-white no-underline flex items-center hover:bg-green-500" %>
        
      <%else%>
            <%= link_to "Sign Out",destroy_user_session_path, data:{turbo_method: :delete} ,class:"flex-no-grow flex-no-shrink relative py-2 px-4 leading-normal text-white no-underline flex items-center hover:bg-red-500"%>
            <span class="w-[60px] h-[60px] flex justify-center p-2 rounded overflow-hidden">
            <%if current_user.user_image.attached?%>
              <%=link_to edit_user_registration_path (current_user) ,class:"flex items-center" do%>
                <%=image_tag url_for(current_user.user_image),alt:"Profile",class:"rounded-full h-[40px] h-[40px]" %>
              <%end%>
            <%else%>
               <%=link_to edit_user_registration_path(current_user) ,class:"flex items-center p-3 " do%>
                <span class="rounded-full bg-black p-2 w-[50px] h-[50px] text-white flex justify-center items-center"><%=current_user.username[0].upcase%></span>
                <%end%>
            <%end%>
          </span>
        <%end%>
      
    </div>
  </div>
</nav>


<!-- component -->
<!-- This is an example component -->
    <style>

        input:checked ~ .dot {
        transform: translateX(100%);
        /* background-color: #132b50; */
        }
    </style>

<script>
    function darkModeListener() {
        // Add this to check

    document.querySelector("html").classList.toggle("dark");
    document.querySelector("body").classList.toggle("dark");
    // console.log("habi")
    
    }
  //   function toggleDark() {
  //   if (document.documentElement.classList.contains('dark')) {
  //     document.documentElement.classList.remove('dark');
  //     console.log("clicked")
      
  //     //localStorage.setItem("theme", "light");
  //   } else {
  //     document.documentElement.classList.add('dark');
  //     //localStorage.setItem("theme", "dark");
  //     console.log("cli")
  //   }
  // }

    document.querySelector("input[type='checkbox']#dark-toggle").addEventListener("click", darkModeListener);


</script>

app/views/shared/_note.html.erb
<%=turbo_frame_tag "note_#{note.id}" do%>
<div class="border rounded-md shadow-xl p-4  m-4 mb-3 hover:scale-105 hover:ease-in-out transition duration-300 ">
                    <div class="flex justify-between gap-1 mb-2">
                        <%if current_user.id == note.user_id%>
                        <%#if current%>
                        <%# current_user.inspect%>
                        <%#"#{current_user.id} , #{note.user_id}%>
                            <%=link_to edit_note_path(note),class:"text-green-300 hover:text-green-600 " do%>
                                <i class="fa-regular fa-pen-to-square"></i>
                            <%end%>
                            <%=link_to note_path(note),data:{turbo_frame: "content"},class:"text-blue-300 hover:text-blue-600 hidden md:block" do%>
                                <i class="fa-solid fa-book-open"></i>
                            <%end%>
                            <%=link_to note_path(note) ,data:{turbo_method: :delete,turbo_confirm: "Confirm Deletion of this item?"},class:"text-red-300 hover:text-red-500 " do%>
                            <i class="fa-regular fa-trash-can"></i>
                            <%end%>
                        <%else%>
                            <%=link_to note_path(note),data:{turbo_frame: "content"},class:"text-blue-300 hover:text-blue-600 hidden md:block m-auto" do%>
                                <i class="fa-solid fa-book-open"></i>
                            <%end%>
                        <%end%>
                    </div>
                    <%=link_to note_path(note) ,data:{turbo_frame: "_top"} do%>
                    <h2 class="bg-gray-400 break-words text-white text-center p-2 rounded hover:bg-blue-400"> <%=note.title.upcase%> </h2> 
                    <%end%>
                <div class=" text-blue-400 hover:text-blue-600 py-3 px-2">
                    <i class="fas fa-crown"></i> <span class="ml-1"><%=note.user.username.split[0]%></span>
                   
                </div>
                <div class=" flex justify-end items-center text-sm  p-2">
                    <% if note.access == "public" %>
                        <i class="fas fa-globe"></i>
                    <% elsif note.access == "onlyme" %>
                        <i class="fas fa-lock"></i>
                    <% elsif note.access == "friend" %>
                        <i class="fas fa-user-friends"></i>
                    <% end %>
                    <span class="ml-2"><%= note.access.upcase %></span>
                </div>
</div>
<%end%>