config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :api do
    namespace :v1 do
      post "users/sign_in", to: "sessions#create"
      delete "users/sign_out", to: "sessions#destroy"
      post "users/sign_up", to: "registrations#create"
      resources :notes, only: [ :index, :show ]
    end
  end
   
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "notes#index"
  resources :notes, only: [ :index, :create, :edit, :new, :update, :destroy, :show ] do
    post :remove_add_form, on: :collection
    post :remove_content, on: :collection
    # collection do
    #   post :remove_add_form
    #   post :remove_content
    # end
  end
  resources :friendships, only: [ :index, :create, :update, :destroy ] do
    member do
      post :send_friend_request
      post :accept
      post :reject
      delete :remove_friend
    end

    collection do
      get :pending_requests
    end
  end
end

app/models/friendship.rb
# == Schema Information
#
# Table name: friendships
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  friend_id  :integer          not null
#  status     :string           default("pending")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
  validates :status, inclusion: { in: [ "pending", "accepted", "rejected" ] }
  after_create_commit -> { broadcast_prepend_to "requests_#{friend_id}", partial: "friendships/pending_request", locals: { friendship: self }, target: "pending_request" }
  # after_update_commit -> { broadcast_replace_to "home", partial: "friendships/user", locals: { user: self }, target: "user_4" }

  # after_create_commit -> { show_friend_request }

  after_destroy_commit -> { broadcast_remove_to "requests_#{friend_id}", target: "request_#{user_id}" }
  scope :accepted, -> { where(status: "accepted") }

  def show_friend_request
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.where.not(id: current_user.id)
    @friendship = Friendship.last
  end
  def create
    friend = User.find(params[:friend_id])
    current_user.send_friend_request(friend)
    respond_to do |format|
      format.html { redirect_to friendships_path(friend), notice: "Friend request sent!" }
      # format.turbo_stream
    end
  end

  def update
    friend = User.find(params[:friend_id])
    current_user.accept_friend_request(friend)
    redirect_to friendships_path(friend), notice: "Friend request accepted!"
  end

  def destroy
    request = Friendship.find(params[:id])
    request.destroy
    redirect_to friendships_path, notice: "Friendship request Cancelled."
  end

  def send_friend_request
    friend = User.find(params[:id])

    if current_user == friend
      flash[:error] ="You can't send a friend request to yourself"
      redirect_to friendships_path and return
    end
    current_user.send_friend_request(friend)
    flash[:notice]="Friend request sent to #{friend.username}"
    redirect_to friendships_path
  end

  def remove_friend
    friend = User.find(params[:id])
    friendship = current_user.friendships.find_by(friend_id: friend.id)
    if friendship.nil?
      friendship = current_user.inverse_friendships.find_by(user_id: friend.id)
    end

    if friendship
      friendship.destroy
      flash[:notice] = "You are no longer friends with #{friend.username}"
    else
      flash[:error]= "You are not friends with #{friend.username}"
    end
    redirect_to friendships_path
  end


  def pending_requests
    @pending_requests = current_user.inverse_friendships.where(status: "pending")

    puts "test #{@pending_requests}"
    # @friendship = Friendship.last

    # render locals: { friendship: @friendship,  }
  end

  def accept
    friendship = Friendship.find(params[:id])
    if friendship.update(status: "accepted")
      redirect_to pending_requests_friendships_path, notice: "Friend request accepted."
    else
      redirect_to pending_requests_friendships_path, alert: " Could not Accept Friend request."
    end
  end

  def reject
    friendship = Friendship.find(params[:id])
    if friendship.update(status: "rejected")
      redirect_to pending_requests_friendships_path, notice: "Friend request rejected."
    else
      redirect_to pending_requests_friendships_path, alert: " Could not Reject Friend request."
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_pendingRequest.html.erb
<%=turbo_frame_tag "request_#{friendship}" do%>
<div class="border rounded p-2 mb-2 flex space-between m-2 items-center shadow-md w-[90%] mx-auto rounded-xl">
            <%# image_tag friendship.user.user_image.variant(resize_to_limit: [50, 50]).processed, alt: "Profile" if friendship.user.user_image.attached? %>
            <div class="h-10 w-10 md:h-16 md:w-16 m-2 rounded-full overflow-hidden border">
            <%if friendship.user.user_image.attached?%>
                <%= image_tag friendship.user.user_image, alt: "#{friendship.user.username} Profile" ,class:"object-cover w-full h-full" %>
            <%else%>
            <%= image_tag 'https://img.freepik.com/free-photo/portrait-white-man-isolated_53876-40306.jpg', alt: "Default Profile",class:"object-cover w-full h-full" %>
            <% end %>
        </div>
            <p class="text-lg md:text-xl lg:text-2xl font-semibold p-3"><%= friendship.user.username %></p>
            <div class="flex ml-auto">

                <%= button_to 'Accept', accept_friendship_path(friendship), method: :post, class: " ml-auto border text-white bg-blue-300 border-blue-400 p-3 rounded hover:bg-green-500 hover:text-white" %>
                <%= button_to 'Reject', reject_friendship_path(friendship), method: :post, class: "border bg-blue-300 text-white border-blue-400 mx-2 p-3 rounded hover:bg-red-500 hover:text-white " %>
            </div>
        </div>

<%end%>

app/views/friendships/_pending_request.html.erb
<%=turbo_frame_tag "request_#{friendship.user_id}" do%>
    <div class="border rounded p-2 mb-2 flex space-between m-2 items-center shadow-md">
        <%# image_tag friendship.user.user_image.variant(resize_to_limit: [50, 50]).processed, alt: "Profile" if friendship.user.user_image.attached? %>
        <div class="h-10 w-10 md:h-16 md:w-16 m-2 rounded-full overflow-hidden border">
        <%if friendship.user.user_image.attached?%>
            <%= image_tag friendship.user.user_image, alt: "#{friendship.user.username} Profile" ,class:"object-cover w-full h-full" %>
        <%else%>
        <%= image_tag 'https://img.freepik.com/free-photo/portrait-white-man-isolated_53876-40306.jpg', alt: "Default Profile",class:"object-cover w-full h-full" %>
        <% end %>
    </div>
        <p class="text-lg md:text-xl lg:text-2xl font-semibold p-3"><%= friendship.user.username %></p>
        <div class="flex ml-auto">

            <%= button_to 'Accept', accept_friendship_path(friendship), method: :post, class: " ml-auto border bg-blue-300 border-blue-400 p-3 rounded hover:bg-green-500 hover:text-white",data:{turbo_frame:"user_4}"} %>
            <%= button_to 'Reject', reject_friendship_path(friendship), method: :post, class: "border bg-blue-300 border-blue-400 mx-2 p-3 rounded hover:bg-red-500 hover:text-white ",data:{turbo_frame:"user_4"} %>
        </div>
    </div>

    <%end%>

app/views/friendships/_user.html.erb
<%=turbo_frame_tag "user_#{user.id}" do%>
<div class="border rounded-lg p-2 bg-gradient-to-r from-teal-400 to-yellow-200 shadow-slate-500">
        <div class="relative mx-4 mt-4 overflow-hidden rounded-xl h-36 lg:h-72 bg-blue-700">
        <%if user.user_image.attached?%>
            <%= image_tag user.user_image, alt: "#{user.username} Profile" ,class:"object-cover w-full h-full" %>
        <%else%>
        <%= image_tag 'https://img.freepik.com/free-photo/portrait-white-man-isolated_53876-40306.jpg', alt: "Default Profile",class:"object-cover w-full h-full" %>
        <% end %>
        </div>
        <p class="px-3 py-2 text-center font-bold text-xl lg:text-2xl"><%=user.username%> </p>
        <% # Check if the current user already sent a freind request to this user or vice versa%>
        <div class="w-[90%] mx-auto">
        <%friendship = current_user.friendships.find_by(friend_id: user.id)%>
        <%if current_user.friend?(user.id)%>
            <p class="bg-green-300 p-2 border border-white rounded pl-4">Friends</p>
            <%=button_to  remove_friend_friendship_path(user),method: :delete,class:"rounded p-2 m-2 mx-auto w-full bg-blue-400 text-white hover:bg-blue-600 border border-white" do%>
            <i class="fas fa-user-minus"></i> <span class="ml-1"> Remove Friend</span>
            <%end%>
        <%elsif friendship.nil?%>
            <%=button_to  send_friend_request_friendship_path(user),method: :post,class:"rounded p-2 m-2 bg-blue-400 text-white hover:bg-blue-600 border border-white mx-auto w-full" do%>
            <i class="fas fa-user-plus"></i> <span class="ml-1"> Add Friend</span>
            <%end%>

        <%elsif friendship.status == 'pending'%>
            <p class="bg-blue-300 p-2 border border-white rounded">Friend request pending......</p>
            <%=button_to  friendship_path(friendship),method: :delete,class:"rounded p-2 bg-blue-400 text-white hover:bg-blue-600 m-2 border border-white w-full mx-auto" do%>
                <i class="fas fa-user-times"></i>
                <span class="ml-1">Cancel Request</span>
            <%end%>
        
        <%else%>
            <p class="bg-red-300 p-2">Friendship rejected</p>
        <%end%>
        </div>
    </div>

    <%end%>

app/views/friendships/create.turbo_stream.erb
<%#turbo_stream.prepend "pending_request","pending_request",friendship:friend%>

app/views/friendships/index.html.erb
<%=turbo_stream_from "home"%>
<h1 class="text-center p-3 font-bold text-2xl">All Users</h1>
<div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2 w-[90%] mx-auto ">

<% @users.each do |user|%>
    <%=render "user",user:user%>
<%end%>
</div>

app/views/friendships/pending_requests.html.erb
<%=turbo_stream_from "requests_#{current_user.id}"%>
<%if @pending_requests.empty?%>
    <h2 class="text-center font-semibold text-2xl text-center">No Friend requests.</h2>
<%else%>

    <h2 class="text-center font-semibold text-2xl text-center">Pending Friend Requests</h2>
    <%#turbo_frame_tag "pending_request" do%>
    <div id="pending_request">
        <%# if friendship%>
            <%@pending_requests.each do |friendship| %>
            <%=render "friendships/pending_request",friendship:friendship%>
        <% end %>
        <%#end %>
    </div>
    <%#end%>
<%end%>